/**
 * ScholarHub - Dữ liệu demo môn học & tài liệu (FIT-DNU)
 */
const SEED_SUBJECTS = [
    { id: "1", ten_mon_hoc: "Cấu trúc dữ liệu & Giải thuật", ma_mon_hoc: "FIT201", khoa_vien: "CNTT", so_tin_chi: 3, mo_ta: "Stack, Queue, Tree, Sort, Graph" },
    { id: "2", ten_mon_hoc: "Giải tích 1", ma_mon_hoc: "MATH101", khoa_vien: "Khoa học cơ bản", so_tin_chi: 4, mo_ta: "Giới hạn, đạo hàm, tích phân" },
    { id: "3", ten_mon_hoc: "Đại số tuyến tính", ma_mon_hoc: "MATH102", khoa_vien: "Khoa học cơ bản", so_tin_chi: 3, mo_ta: "Ma trận, không gian vector" },
    { id: "4", ten_mon_hoc: "Lập trình hướng đối tượng", ma_mon_hoc: "FIT302", khoa_vien: "CNTT", so_tin_chi: 3, mo_ta: "Java/OOP, design patterns cơ bản" },
    { id: "5", ten_mon_hoc: "Cơ sở dữ liệu", ma_mon_hoc: "FIT303", khoa_vien: "CNTT", so_tin_chi: 3, mo_ta: "SQL, ER, chuẩn hóa" },
    { id: "6", ten_mon_hoc: "Triết học Mác-Lênin", ma_mon_hoc: "SSH1110", khoa_vien: "Lý luận chính trị", so_tin_chi: 2, mo_ta: "Ôn thi trắc nghiệm" }
];

const SEED_DOCUMENTS = [
    {
        tieu_de: "Đề thi cuối kỳ CTDL & Giải thuật K65",
        id_mon_hoc: 1,
        loai_tai_lieu: "Đề thi",
        nguoi_dang: "Nguyễn Văn An",
        duong_dan_file: "https://drive.google.com/file/d/1example-ctdl",
        anh_bia: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600&h=400&fit=crop",
        so_luot_xem: 842,
        so_luot_tai: 210,
        diem_danh_gia: 4.7,
        tu_khoa: "#ctdl #dek65 #onsap",
        nam_hoc: "2024-2025",
        mo_ta: "Đề thi có lời giải chi tiết: sort, tree, graph BFS/DFS.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-01-10"
    },
    {
        tieu_de: "Slide bài giảng CTDL - Chương Tree & Graph",
        id_mon_hoc: 1,
        loai_tai_lieu: "Slide bài giảng",
        nguoi_dang: "ThS. Trần Minh",
        duong_dan_file: "https://drive.google.com/file/d/2slide-ctdl",
        anh_bia: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop",
        so_luot_xem: 1205,
        so_luot_tai: 430,
        diem_danh_gia: 4.9,
        tu_khoa: "#slide #tree #graph",
        nam_hoc: "2024-2025",
        mo_ta: "Slide đầy đủ minh họa AVL, BST, Dijkstra.",
        gia_xu: 15,
        trang_thai: "Approved",
        ngay_tao: "2025-02-01"
    },
    {
        tieu_de: "Ghi chép Giải tích 1 - Tích phân & ứng dụng",
        id_mon_hoc: 2,
        loai_tai_lieu: "Ghi chép",
        nguoi_dang: "Lê Thị Hoa",
        duong_dan_file: "https://drive.google.com/file/d/3gt1",
        anh_bia: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop",
        so_luot_xem: 956,
        so_luot_tai: 188,
        diem_danh_gia: 4.6,
        tu_khoa: "#giaitich #tichphan",
        nam_hoc: "2024-2025",
        mo_ta: "Tóm tắt công thức và bài tập hay gặp.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-01-15"
    },
    {
        tieu_de: "Đề thi Giải tích 1 HK2 - Đại Nam 2024",
        id_mon_hoc: 2,
        loai_tai_lieu: "Đề thi",
        nguoi_dang: "Phạm Đức Bình",
        duong_dan_file: "https://drive.google.com/file/d/4gt-de",
        anh_bia: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&h=400&fit=crop",
        so_luot_xem: 678,
        so_luot_tai: 145,
        diem_danh_gia: 4.5,
        tu_khoa: "#de thi #giaitich",
        nam_hoc: "2023-2024",
        mo_ta: "Đề chính thức kèm đáp án.",
        gia_xu: 20,
        trang_thai: "Approved",
        ngay_tao: "2024-12-20"
    },
    {
        tieu_de: "Đại số tuyến tính - Ma trận & Định thức (full)",
        id_mon_hoc: 3,
        loai_tai_lieu: "Tài liệu tham khảo",
        nguoi_dang: "Hoàng Tuấn",
        duong_dan_file: "https://drive.google.com/file/d/5dstt",
        anh_bia: "https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&h=400&fit=crop",
        so_luot_xem: 534,
        so_luot_tai: 98,
        diem_danh_gia: 4.4,
        tu_khoa: "#dstt #ma tran",
        nam_hoc: "2024-2025",
        mo_ta: "Ebook ngắn gọn, dễ ôn.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-03-01"
    },
    {
        tieu_de: "Bài tập ĐSTT có lời giải - Chương không gian vector",
        id_mon_hoc: 3,
        loai_tai_lieu: "Ghi chép",
        nguoi_dang: "Vũ Minh Châu",
        duong_dan_file: "https://drive.google.com/file/d/6dstt-bt",
        anh_bia: "https://images.unsplash.com/photo-1632571401175-05c646b98af6?w=600&h=400&fit=crop",
        so_luot_xem: 412,
        so_luot_tai: 76,
        diem_danh_gia: 4.3,
        tu_khoa: "#dstt #bai tap",
        nam_hoc: "2024-2025",
        mo_ta: "50+ bài tập chọn lọc.",
        gia_xu: 10,
        trang_thai: "Approved",
        ngay_tao: "2025-02-14"
    },
    {
        tieu_de: "OOP Java - Lab & Project mẫu",
        id_mon_hoc: 4,
        loai_tai_lieu: "Slide bài giảng",
        nguoi_dang: "Trần Thị Lan",
        duong_dan_file: "https://drive.google.com/file/d/7oop",
        anh_bia: "https://images.unsplash.com/photo-1517694712202-14dd953757aa?w=600&h=400&fit=crop",
        so_luot_xem: 889,
        so_luot_tai: 201,
        diem_danh_gia: 4.8,
        tu_khoa: "#java #oop",
        nam_hoc: "2024-2025",
        mo_ta: "Source code quản lý sinh viên mẫu.",
        gia_xu: 25,
        trang_thai: "Approved",
        ngay_tao: "2025-01-20"
    },
    {
        tieu_de: "Đề cương ôn thi Cơ sở dữ liệu",
        id_mon_hoc: 5,
        loai_tai_lieu: "Tài liệu tham khảo",
        nguoi_dang: "Nguyễn Hữu Đạt",
        duong_dan_file: "https://drive.google.com/file/d/8csdl",
        anh_bia: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&h=400&fit=crop",
        so_luot_xem: 623,
        so_luot_tai: 134,
        diem_danh_gia: 4.6,
        tu_khoa: "#csdl #sql",
        nam_hoc: "2024-2025",
        mo_ta: "ER, SQL, transaction, index.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-02-28"
    },
    {
        tieu_de: "SQL nâng cao - Stored Procedure & Trigger",
        id_mon_hoc: 5,
        loai_tai_lieu: "Ghi chép",
        nguoi_dang: "Lý Văn Em",
        duong_dan_file: "https://drive.google.com/file/d/9sql",
        anh_bia: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
        so_luot_xem: 445,
        so_luot_tai: 89,
        diem_danh_gia: 4.5,
        tu_khoa: "#sql #nangcao",
        nam_hoc: "2024-2025",
        mo_ta: "Ví dụ MySQL thực hành.",
        gia_xu: 12,
        trang_thai: "Approved",
        ngay_tao: "2025-03-10"
    },
    {
        tieu_de: "Trắc nghiệm Triết học Mác-Lênin (200 câu)",
        id_mon_hoc: 6,
        loai_tai_lieu: "Đề thi",
        nguoi_dang: "Đoàn Kế Tài",
        duong_dan_file: "https://drive.google.com/file/d/10triet",
        anh_bia: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=400&fit=crop",
        so_luot_xem: 1560,
        so_luot_tai: 520,
        diem_danh_gia: 4.7,
        tu_khoa: "#triet #tracnghiem",
        nam_hoc: "2024-2025",
        mo_ta: "Bộ câu hỏi hay ra thi cuối kỳ.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-01-05"
    },
    {
        tieu_de: "Mindmap ôn Triết học Mác-Lênin",
        id_mon_hoc: 6,
        loai_tai_lieu: "Ghi chép",
        nguoi_dang: "Phạm Thị Yến",
        duong_dan_file: "https://drive.google.com/file/d/11triet-map",
        anh_bia: "https://images.unsplash.com/photo-1524995997942-a1c2e516a42f?w=600&h=400&fit=crop",
        so_luot_xem: 712,
        so_luot_tai: 167,
        diem_danh_gia: 4.4,
        tu_khoa: "#triet #mindmap",
        nam_hoc: "2024-2025",
        mo_ta: "Sơ đồ tư duy toàn bộ môn.",
        gia_xu: 8,
        trang_thai: "Approved",
        ngay_tao: "2025-02-05"
    },
    {
        tieu_de: "Đề thi giữa kỳ CTDL - Có đáp án",
        id_mon_hoc: 1,
        loai_tai_lieu: "Đề thi",
        nguoi_dang: "Bùi Quang Huy",
        duong_dan_file: "https://drive.google.com/file/d/12ctdl-gk",
        anh_bia: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&h=400&fit=crop",
        so_luot_xem: 398,
        so_luot_tai: 67,
        diem_danh_gia: 4.2,
        tu_khoa: "#ctdl #giua ky",
        nam_hoc: "2024-2025",
        mo_ta: "Đề GK kèm lời giải ngắn.",
        gia_xu: 0,
        trang_thai: "Approved",
        ngay_tao: "2025-03-15"
    }
];

const SEED_DEMO_USERS = [
    {
        ho_ten: "Sinh viên Demo",
        email: "demo@dnu.edu.vn",
        mat_khau: "123456",
        truong_hoc: "Đại học Đại Nam",
        so_xu: 100,
        diem_tich_luy: 120,
        ten_dang_nhap: "demo",
        anh_dai_dien: "https://api.dicebear.com/7.x/avataaars/svg?seed=Demo"
    }
];
